-- AlterTable
ALTER TABLE `chatlog` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `role` ADD COLUMN `originServerid` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `roleinfo` ADD COLUMN `merge` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `serverinfo` ADD COLUMN `nodeid` SMALLINT UNSIGNED NOT NULL DEFAULT 1;
